// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.gov.nsw.records.digitalarchives.dashboard.model;

import au.gov.nsw.records.digitalarchives.dashboard.model.FileStorage;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect FileStorage_Roo_Configurable {
    
    declare @type: FileStorage: @Configurable;
    
}
